title: 7 letters for 1 word
subtitle: Just like Scrabble©
description: >- # this means to ignore newlines until "baseurl:"
  This is the site for '7 letters for 1 word' landing page
author: R. Aubel
email: aubel.r@gmail.com
avatar: assets/images/avatar.png

baseurl: ""                     # the subpath of your site, e.g. /blog
url: https://aubel-r.github.io  # the base hostname & protocol for your site

defaults:
  - scope:
      path: "assets/apk"
    values:
      apk: true